# Generated by Django 3.1.1 on 2020-09-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.source')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['url'], name='article_art_url_8775f8_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['header'], name='article_art_header_c906bc_idx'),
        ),
    ]
