# Generated by Django 3.1.1 on 2020-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200929_1520'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='article',
            name='unique source url',
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['name'], name='article_sou_name_b3d7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['url'], name='article_sou_url_6f9737_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('url',), name='unique article url'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('url',), name='unique source url'),
        ),
    ]
