# Generated by Django 3.1.2 on 2020-10-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200929_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='users',
        ),
    ]
