# Generated by Django 3.1.2 on 2020-10-11 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_remove_article_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='source',
            name='subscribers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
