# Generated by Django 3.1.2 on 2020-10-11 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_auto_20201011_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='source',
            name='subscribers',
            field=models.ManyToManyField(null=True, related_name='sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
