# Generated by Django 3.1.2 on 2020-10-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20201012_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
