# Generated by Django 3.1.2 on 2020-10-11 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201011_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSource',
        ),
    ]
