# Generated by Django 3.1.2 on 2020-10-12 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0014_remove_source_subscribers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_delete_usersource'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_order', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-source_order'],
            },
        ),
    ]
