# Generated by Django 3.1.2 on 2020-10-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201012_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersources',
            options={'ordering': ['source_order']},
        ),
    ]
