# Generated by Django 3.1.2 on 2020-10-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201012_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersources',
            name='source_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
